name = "telepost-worker"
main = "src/index.ts"
compatibility_date = "2024-05-29"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "production"
APP_URL = "https://telepost.app"

[[d1_databases]]
binding = "DB"
database_name = "telepost-db"
database_id = "4b8cc808-c650-4b4b-ad31-1acbd3055b12"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "telepost-media"

[triggers]
crons = ["* * * * *"]
